plugins {
    id "com.android.application"
}

android {
    namespace "com.sarn.armox"
    compileSdk 34

    defaultConfig {
        applicationId "com.sarn.armox"
        minSdk 24
        targetSdk 34
        versionCode 181
        versionName "1.8.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            applicationIdSuffix ""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.webkit:webkit:1.11.0"
}
